name: Format Change Log

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
      - dev  # Customize to your needs

jobs:
  format-change-log:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Extract and Format Commit Messages
        id: format_commits
        run: |
          # Extract commit messages, skipping merge commits, for the last 5 commits
          commits=$(git log -5 --pretty=format:"%s (%h)" --no-merges)

          # Initialize formatted change log
          change_log="Change Log\n=--------------------------"

          # Process each commit message
          while IFS= read -r commit; do
            formatted_commit=$(echo "$commit" | sed -E 's/^(.+?): /- \1: /')
            change_log="${change_log}\n${formatted_commit}"
          done <<< "$commits"

          # Output formatted change log with preserved newlines
          echo -e "$change_log"
          echo "::set-output name=change_log::$change_log"

      - name: Install GitHub CLI
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Required for GitHub CLI installation via npm

      - name: Install GitHub CLI via npm
        run: npm install -g @cli/cli

      - name: Update Pull Request Description
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Use the GitHub API to update the pull request description
          pr_number=${{ github.event.pull_request.number }}
          change_log="${{ steps.format_commits.outputs.change_log }}"
          
          # Fetch the current PR description
          current_description=$(gh pr view "$pr_number" --json body -q ".body")

          # Update the PR description with the Change Log at the bottom
          new_description="${current_description}\n\n${change_log}"
          
          # Update the PR description using the GitHub CLI
          gh pr edit "$pr_number" --body "$new_description"
