name: Update PR Description Based on Commits

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  update-pr-description:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Generate Pull Request Description
      id: pr-description
      uses: octue/generate-pull-request-description@1.0.0.beta-2
      with:
        pull_request_url: ${{ github.event.pull_request.url }}
        api_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Format Change Log
      id: format-changelog
      run: |
        # Initialize the Change Log with a clean header
        description="### Change Log\n\n"

        # Add each commit message to the Change Log as an item
        while read -r line; do
          description+="- $line\n"
        done <<< "${{ steps.pr-description.outputs.pull_request_description }}"

        # Set the formatted description without extra autogenerated text
        echo "formatted_description=$description" >> $GITHUB_ENV

    - name: Update Pull Request Body
      uses: riskledger/update-pr-description@v2
      with:
        body: ${{ env.formatted_description }}
        token: ${{ secrets.GITHUB_TOKEN }}
