name: Format Commit Description

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
      - dev  # Run this on the main and dev branches, or specify others as needed
      - Team

jobs:
  format-description:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Extract Commit Messages
        id: extract_commits
        run: |
          # Get commit messages
          COMMIT_MESSAGES=$(git log -1 --pretty=%B)
          
          # Format messages nicely (for example, adding bullet points)
          FORMATTED_COMMIT_MESSAGES=$(echo "$COMMIT_MESSAGES" | sed 's/^/- /')
          
          # Set the formatted message as an output for later steps
          echo "::set-output name=formatted_commit_messages::$FORMATTED_COMMIT_MESSAGES"

      - name: Set Pull Request Description
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### 📝 Commit Description
            ${{ steps.extract_commits.outputs.formatted_commit_messages }}
