name: Format Change Log

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
      - dev  # Customize to your needs

jobs:
  format-change-log:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Extract and Format Commit Messages
        id: format_commits
        run: |
          # Extract the last 5 commit messages for formatting
          commits=$(git log -5 --pretty=format:"%s (%h)")

          # Format as Change Log
          change_log="### Change Log\n=--------------------------"
          
          # Process each commit message
          while IFS= read -r commit; do
            formatted_commit=$(echo "$commit" | sed -E 's/^(.+?): /- \1: /')
            change_log="${change_log}\n${formatted_commit}"
          done <<< "$commits"

          # Output formatted log
          echo -e "$change_log"
          echo "::set-output name=change_log::$change_log"

      - name: Post Change Log to Pull Request
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.format_commits.outputs.change_log }}
