name: Update PR Description Based on Commits

on:
  pull_request_target:
    types: [opened, synchronize, reopened, closed]
    branches:
      - dev

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  update-pr-description:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get PR Number and Commit Messages
      id: get_commits
      run: |
        echo "## Retrieving PR Details..."
        PR_NUMBER=${{ github.event.pull_request.number }}
        COMMITS=$(gh pr view $PR_NUMBER --json commits --jq '.commits[].commit | "- " + .message')
        
        echo "::set-output name=pr_number::$PR_NUMBER"
        echo "::set-output name=commits::$COMMITS"

    - name: Update PR Description
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const prNumber = ${{ steps.get_commits.outputs.pr_number }};
          const commitMessages = `### Commits:\n${{ steps.get_commits.outputs.commits }}`;
          
          const newDescription = `### Pull Request Summary:\n\n${commitMessages}\n\n---\n_Merged to dev._`;
          
          await github.rest.pulls.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber,
            body: newDescription
          });

    - name: Display Confirmation
      run: echo "Pull Request description updated successfully."
