name: Generate Change Log

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract Commit Messages
        id: extract_commits
        run: |
          # Fetch commit messages from the latest commits (e.g., last 20)
          COMMIT_MESSAGES=$(git log -n 20 --pretty=format:"%s" | grep -E "^(hotfix|fix|feat|edit)")
          
          # Format the commit messages as per requirement
          FORMATTED_CHANGE_LOG="Change Log\n"
          while IFS= read -r COMMIT; do
            # Capture the issue number and title
            ISSUE_NUMBER=$(echo "$COMMIT" | grep -oE '#[0-9]+')
            FORMATTED_COMMIT="${COMMIT^} (${COMMIT} ${ISSUE_NUMBER})"
            
            FORMATTED_CHANGE_LOG+="${FORMATTED_COMMIT}\n"
          done <<< "$COMMIT_MESSAGES"
          
          # Save the result as output
          echo "formatted_change_log<<EOF" >> $GITHUB_ENV
          echo -e "$FORMATTED_CHANGE_LOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Display Change Log
        run: |
          echo -e "${{ env.formatted_change_log }}"
