name: Checks

on:
  pull_request:

jobs:
  commits_check_job:
    runs-on: ubuntu-latest
    name: Commits Check
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Get PR Commits
        id: 'get-pr-commits'
        uses: luizgustavosaraiva/get-pull-requests-commits@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Format Changelog
        id: changelog
        run: |
          formatted_changelog=$(echo "${{ steps.get-pr-commits.outputs.commits }}" | jq -r '.[] | "* \(.message) (#\(.number))"')
          echo "::set-output name=formatted_change_log::$formatted_changelog"

      - name: Update Pull Request or Issue Description
        uses: blablacar/action-sticky-description@master
        with:
          issue_number: ${{ github.event.number }}
          message: |
            Change Log:
            ${{ steps.changelog.outputs.formatted_change_log }}
