name: Update PR Description Based on Commits

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]  # Trigger on PR creation, update, or reopen

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  update-pr-description:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Generate Pull Request Description
      id: pr-description
      uses: octue/generate-pull-request-description@1.0.0.beta-2
      with:
        pull_request_url: ${{ github.event.pull_request.url }}
        api_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Format Change Log
      id: format-changelog
      run: |
        # Prepare a nicely formatted "Change Log" section
        description="### Change Log\n\n"
        description+="Here is a summary of the changes included in this pull request:\n\n"

        # Format each commit message as an itemized list
        while read -r line; do
          description+="- $line\n"
        done <<< "${{ steps.pr-description.outputs.pull_request_description }}"

        description+="\n---\n_Automatically generated summary._\n"

        # Save the formatted description as an output
        echo "formatted_description=$description" >> $GITHUB_ENV

    - name: Update Pull Request Body
      uses: riskledger/update-pr-description@v2
      with:
        body: ${{ env.formatted_description }}
        token: ${{ secrets.GITHUB_TOKEN }}
