name: Update PR Description Based on Commits

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  update-pr-description:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Generate Change Log
      id: changelog
      run: |
        echo "### Change Log" > changelog.md
        echo "" >> changelog.md
        git log --format="- %s" origin/main..HEAD >> changelog.md
        changelog=$(cat changelog.md)
        echo "changelog=$changelog" >> $GITHUB_ENV

    - name: Update Pull Request Description
      uses: kt3k/update-pr-description@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_body: ${{ env.changelog }}
