name: Update PR Description Based on Commits

on:
  pull_request:
    types: [opened, synchronize, reopened,closed]  # Trigger on PR creation, update, or reopen

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  update-pr-description:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: |
        echo "Installing GitHub CLI..."
        sudo apt update
        sudo apt install -y gh
        gh auth login --with-token <<< "${{ secrets.TOKEN }}"

    - name: Get PR Number and Commit Messages
      id: get_commits
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        
        # Fetch commit messages and format as bullet points
        COMMITS=$(gh pr view $PR_NUMBER --json commits --jq '.commits[].commit.message' | sed 's/^/- /')
        
        echo "commits=$COMMITS" >> $GITHUB_ENV
        echo "pr_number=$PR_NUMBER" >> $GITHUB_ENV

    - name: Update PR Description
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.TOKEN }}
        script: |
          const prNumber = process.env.PR_NUMBER;
          const commits = process.env.COMMITS;
          
          const newDescription = `### Pull Request Summary:\n\n### Commits:\n${commits}\n\n---\n_Automatically generated summary._`;
          
          await github.rest.pulls.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber,
            body: newDescription
          });

    - name: Display Confirmation
      run: echo "Pull Request description updated successfully."
