name: Update PR Description Based on Commits

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  update-pr-description:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Generate Pull Request Description
      id: pr-description
      uses: octue/generate-pull-request-description@1.0.0.beta-2
      with:
        pull_request_url: ${{ github.event.pull_request.url }}
        api_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Format Change Log
      id: format-changelog
      run: |
        # Initialize description with a header
        description="### Change Log\n\n**Summary of Changes:**\n\n"

        # Extract commit messages and format each one as an itemized list
        while read -r line; do
          description+="- $line\n"
        done <<< "${{ steps.pr-description.outputs.pull_request_description }}"

        # Add a separator and auto-generated note
        description+="\n---\n_Automatically generated summary._\n"

        # Set the output for use in the next step
        echo "formatted_description=$description" >> $GITHUB_ENV

    - name: Update Pull Request Body
      uses: riskledger/update-pr-description@v2
      with:
        body: ${{ env.formatted_description }}
        token: ${{ secrets.GITHUB_TOKEN }}
