name: Example Workflow

on: pull_request

jobs:
  example_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write  # Modify as needed
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use GITHUB_TOKEN with GitHub CLI
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Example command using the GitHub CLI
        gh issue create --title "Test Issue" --body "This is a test issue created by GitHub Actions."
