name: Update Description with Changelog

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  update-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Generate Changelog
        id: changelog
        run: |
          changelog=$(git log -n 5 --pretty=format:"* %s (%h)" --abbrev-commit)
          echo "::set-output name=formatted_change_log::$changelog"

      - name: Update Pull Request or Issue Description
        uses: blablacar/action-sticky-description@master
        with:
          issue_number: ${{ github.event.number }}
          message: |
            Change Log:
            ${{ steps.changelog.outputs.formatted_change_log }}
